#!/usr/bin/env bash
set -euo pipefail

###############################################################################
# generate-crew-bootstrap.sh — AI Crew Bootstrap Script Generator
#
# Reads .env and environments.json from the repo root and generates a
# self-contained bash script that, when run as root on a fresh Ubuntu 22.04
# VM, installs Node.js 20, clones and builds ai-crew, writes the config
# files, and wires the crew as a persistent systemd service.
#
# Set up your .env and environments.json as you would for a local run, then:
#
#   ./scripts/generate-crew-bootstrap.sh > /tmp/crew-bootstrap.sh
#   sudo ./vm-setup.sh --name crew-1 --bootstrap /tmp/crew-bootstrap.sh
#   rm /tmp/crew-bootstrap.sh   # contains secrets — delete after use
#
# The generated script is written to stdout; all logging goes to stderr.
###############################################################################

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# ─── Logging (all to stderr so stdout stays clean for the generated script) ──

RED='\033[0;31m'
YELLOW='\033[1;33m'
GREEN='\033[0;32m'
NC='\033[0m'

info()  { echo -e "${GREEN}[INFO]${NC} $*" >&2; }
warn()  { echo -e "${YELLOW}[WARN]${NC} $*" >&2; }
error() { echo -e "${RED}[ERROR]${NC} $*" >&2; }

# ─── Usage ───────────────────────────────────────────────────────────────────

usage() {
    cat <<EOF >&2
Usage: $(basename "$0") > /tmp/crew-bootstrap.sh

Generate a self-contained bootstrap script for an ai-crew VM deployment.

Reads .env and environments.json from the repo root (set them up as you
would for a local run) and bakes them into a bootstrap script that installs
Node.js 20, clones and builds ai-crew, writes the config files, and registers
ai-crew as a persistent systemd service on an Ubuntu 22.04 VM.

REQUIRED FILES (in repo root: ${REPO_ROOT}):
  .env               — must contain SERVER_BASE_URL, SERVER_USER_PASSWORD, WORK_DIR
  environments.json  — model endpoint configuration

OPTIONS:
  --help   Show this help message and exit

EXAMPLE:
  # 1. Configure as you would for a local run
  cp .env.example .env && \$EDITOR .env
  cp environments.example.json environments.json && \$EDITOR environments.json

  # 2. Generate, deploy, and discard
  ./scripts/generate-crew-bootstrap.sh > /tmp/crew-bootstrap.sh
  sudo ./vm-setup.sh --name crew-1 --bootstrap /tmp/crew-bootstrap.sh
  rm /tmp/crew-bootstrap.sh

NOTE: The generated script embeds secrets in plaintext. Delete it after use.
EOF
}

# ─── CLI argument parsing ────────────────────────────────────────────────────

parse_args() {
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --help)
                usage; exit 0 ;;
            -*)
                error "Unrecognized flag: $1"
                echo "Use --help for usage information." >&2
                exit 1 ;;
            *)
                error "Unrecognized argument: $1"
                echo "Use --help for usage information." >&2
                exit 1 ;;
        esac
    done
}

# ─── File validation ─────────────────────────────────────────────────────────

validate_inputs() {
    local ok=1

    if [[ ! -f "${REPO_ROOT}/.env" ]] || [[ ! -s "${REPO_ROOT}/.env" ]]; then
        error ".env not found or empty at ${REPO_ROOT}/.env"
        error "Copy .env.example to .env and fill in your values."
        ok=0
    fi

    if [[ ! -f "${REPO_ROOT}/environments.json" ]] || [[ ! -s "${REPO_ROOT}/environments.json" ]]; then
        error "environments.json not found or empty at ${REPO_ROOT}/environments.json"
        error "Copy environments.example.json to environments.json and fill in your values."
        ok=0
    fi

    [[ "$ok" -eq 1 ]] || exit 1

    # Verify required .env keys
    local required_keys=("SERVER_BASE_URL" "SERVER_USER_PASSWORD" "WORK_DIR")
    for key in "${required_keys[@]}"; do
        if ! grep -qE "^${key}=.+" "${REPO_ROOT}/.env"; then
            error ".env is missing required key: ${key}"
            ok=0
        fi
    done

    [[ "$ok" -eq 1 ]] || exit 1
}

# ─── Script emission ─────────────────────────────────────────────────────────

emit_bootstrap() {
    local dot_env env_json work_dir

    dot_env=$(<"${REPO_ROOT}/.env")
    env_json=$(<"${REPO_ROOT}/environments.json")
    work_dir=$(grep -E '^WORK_DIR=' "${REPO_ROOT}/.env" | cut -d'=' -f2-)

    cat <<SCRIPT
#!/usr/bin/env bash
set -euo pipefail

# Generated by generate-crew-bootstrap.sh — contains secrets, do not commit.

RED='\033[0;31m'
YELLOW='\033[1;33m'
GREEN='\033[0;32m'
NC='\033[0m'

info()  { echo -e "\${GREEN}[INFO]\${NC} \$*"; }
warn()  { echo -e "\${YELLOW}[WARN]\${NC} \$*" >&2; }
error() { echo -e "\${RED}[ERROR]\${NC} \$*" >&2; }

# ── Idempotency check ────────────────────────────────────────────────────────

if [[ -f /root/ai-crew/.bootstrapped ]]; then
    info "Already bootstrapped — skipping setup."
    exit 0
fi

# ── Step 1: Install Node.js 20 ───────────────────────────────────────────────

info "Installing Node.js 20..."
curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
apt-get install -y nodejs
node --version

# ── Step 2: Clone and build ai-crew ─────────────────────────────────────────

info "Cloning ai-crew..."
git clone https://github.com/syntheticmagus/ai-crew.git /root/ai-crew

info "Building ai-crew..."
cd /root/ai-crew
npm ci
npm run build

# ── Step 3: Write .env ───────────────────────────────────────────────────────

info "Writing .env..."
cat > /root/ai-crew/.env << '__AI_CREW_ENV_EOF__'
${dot_env}
__AI_CREW_ENV_EOF__

# ── Step 3b: Inject this VM's LAN IP as HARBOR_DEPLOY_HOST ────────────────────
# ai-harbor's Caddy (on the host box) reverse-proxies to deployed apps, which run
# here on this VM. It must dial this VM's own LAN IP, so detect it at bootstrap
# time and substitute it for the __HARBOR_DEPLOY_HOST__ sentinel in .env.
if grep -q '__HARBOR_DEPLOY_HOST__' /root/ai-crew/.env; then
    info "Detecting LAN IP for HARBOR_DEPLOY_HOST..."
    DEPLOY_HOST="\$(ip -4 route get 1.1.1.1 2>/dev/null | grep -oP 'src \K[0-9.]+')"
    [[ -z "\$DEPLOY_HOST" ]] && DEPLOY_HOST="\$(hostname -I | awk '{print \$1}')"
    if [[ -z "\$DEPLOY_HOST" ]]; then
        warn "Could not detect LAN IP — set HARBOR_DEPLOY_HOST manually in /root/ai-crew/.env"
    else
        sed -i "s|__HARBOR_DEPLOY_HOST__|\${DEPLOY_HOST}|" /root/ai-crew/.env
        info "HARBOR_DEPLOY_HOST set to \${DEPLOY_HOST}"
    fi
fi

# ── Step 4: Write environments.json ─────────────────────────────────────────

info "Writing environments.json..."
cat > /root/ai-crew/environments.json << '__AI_CREW_ENVJSON_EOF__'
${env_json}
__AI_CREW_ENVJSON_EOF__

# ── Step 5: Create workspace directory ──────────────────────────────────────

info "Creating workspace at ${work_dir}..."
mkdir -p "${work_dir}"

# ── Step 6: Install ai-crew systemd service ──────────────────────────────────

info "Installing ai-crew.service..."
cat > /etc/systemd/system/ai-crew.service << '__AI_CREW_SVC_EOF__'
[Unit]
Description=AI Crew
After=network.target
StartLimitIntervalSec=0

[Service]
Type=simple
User=root
WorkingDirectory=/root/ai-crew
ExecStart=/usr/bin/node dist/index.js
Restart=on-failure
RestartSec=10
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
__AI_CREW_SVC_EOF__

# ── Step 7: Enable and start the service ────────────────────────────────────

info "Enabling and starting ai-crew.service..."
systemctl daemon-reload
systemctl enable ai-crew.service
systemctl start ai-crew.service

touch /root/ai-crew/.bootstrapped

info "Done. Check status with: journalctl -u ai-crew -f"
SCRIPT
}

# ─── Main ────────────────────────────────────────────────────────────────────

main() {
    parse_args "$@"
    validate_inputs
    info "Reading config from ${REPO_ROOT}..."
    emit_bootstrap
    info "Bootstrap script written to stdout." >&2
}

main "$@"
